"""ObjectEligibility: the positive object whitelist.

    approved placement prior
  ∩ Level-1 usable catalog (dataset inventory, not denylisted)
  ∩ size constraints (per-model metadata bbox)
  ∩ current object-interface capability (BDDL taxonomy abilities)

Built on CPU by scripts/tasks/build_eligibility.py into
<build_root>/priors/eligibility_v1.yaml; the planner reads only that file.
Every rejected category is recorded with its reason for review.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional, Protocol

import yaml

ELIGIBILITY_VERSION = 1


class AbilityTaxonomy(Protocol):
    def get_synset_from_category(self, category: str) -> Optional[str]: ...
    def get_abilities(self, synset: str) -> dict: ...
    def get_parents(self, synset: str) -> list[str]: ...
    def get_subtree_categories(self, synset: str) -> list[str]: ...


@dataclass
class ModelRecord:
    model_id: str
    bbox: tuple[float, float, float]

    @property
    def volume(self) -> float:
        return self.bbox[0] * self.bbox[1] * self.bbox[2]


@dataclass
class EligibleCategory:
    category: str
    synset: str
    mass_kg: Optional[float]
    lookalike_keys: list[str]
    models: list[ModelRecord] = field(default_factory=list)

    def model(self, model_id: str) -> ModelRecord:
        for m in self.models:
            if m.model_id == model_id:
                return m
        raise KeyError(f"{self.category}: no eligible model {model_id!r}")


@dataclass
class ObjectEligibility:
    version: int
    source: dict[str, Any]
    categories: dict[str, EligibleCategory]
    rejected: dict[str, str]  # category -> reason

    def is_eligible(self, category: str, model: Optional[str] = None) -> bool:
        c = self.categories.get(category)
        if c is None:
            return False
        return model is None or any(m.model_id == model for m in c.models)

    def lookalike(self, a: str, b: str) -> bool:
        if a == b:
            return True
        ka = set(self.categories[a].lookalike_keys)
        return bool(ka & set(self.categories[b].lookalike_keys))

    def to_dict(self) -> dict[str, Any]:
        cats = {}
        for name in sorted(self.categories):
            c = self.categories[name]
            cats[name] = {"synset": c.synset, "mass_kg": c.mass_kg,
                          "lookalike_keys": list(c.lookalike_keys),
                          "models": {m.model_id: [round(v, 4) for v in m.bbox]
                                     for m in c.models}}
        return {"version": self.version, "source": self.source,
                "categories": cats, "rejected": dict(sorted(self.rejected.items()))}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "ObjectEligibility":
        cats = {}
        for name, c in d["categories"].items():
            cats[name] = EligibleCategory(
                category=name, synset=c["synset"], mass_kg=c.get("mass_kg"),
                lookalike_keys=list(c["lookalike_keys"]),
                models=[ModelRecord(m, tuple(b)) for m, b in sorted(c["models"].items())])
        return cls(version=int(d["version"]), source=dict(d.get("source", {})),
                   categories=cats, rejected=dict(d.get("rejected", {})))

    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "# Object eligibility whitelist (generated by build_eligibility.py).\n"
            + yaml.safe_dump(self.to_dict(), sort_keys=False, width=100),
            encoding="utf-8")

    @classmethod
    def load(cls, path: Path) -> "ObjectEligibility":
        return cls.from_dict(yaml.safe_load(Path(path).read_text(encoding="utf-8")))


def lookalike_keys(category: str, synset: str, taxonomy: AbilityTaxonomy,
                   max_parent_group: int) -> list[str]:
    keys = [f"category:{category}", f"head:{category.split('_')[-1]}"]
    for parent in taxonomy.get_parents(synset) or []:
        if len(taxonomy.get_subtree_categories(parent) or []) <= max_parent_group:
            keys.append(f"parent:{parent}")
    head = synset.split(".")[0]
    if "__" in head:
        keys.append(f"form:{head.split('__')[-1]}")
    return sorted(set(keys))


def build_eligibility(candidate_categories: list[str], taxonomy: AbilityTaxonomy,
                      inventory: dict[str, list[str]], objects_root: Path,
                      avg_specs: dict[str, Any], rules: dict[str, Any],
                      source: dict[str, Any]) -> ObjectEligibility:
    """candidate_categories: categories with >= 1 approved prior.
    inventory: Level-1 usable catalog, category -> model ids."""
    req = set(rules["abilities"]["required"])
    forb = set(rules["abilities"]["forbidden"])
    size = rules["size"]
    cats: dict[str, EligibleCategory] = {}
    rejected: dict[str, str] = {}
    for cat in sorted(set(candidate_categories)):
        if cat not in inventory:
            rejected[cat] = "not in Level-1 usable catalog"
            continue
        syn = taxonomy.get_synset_from_category(cat)
        if not syn:
            rejected[cat] = "no taxonomy synset"
            continue
        abil = set((taxonomy.get_abilities(syn) or {}).keys())
        if not req <= abil:
            rejected[cat] = f"missing abilities {sorted(req - abil)}"
            continue
        if abil & forb:
            rejected[cat] = f"unsupported abilities {sorted(abil & forb)}"
            continue
        mass = (avg_specs.get(cat) or {}).get("mass")
        if mass is not None and mass > rules["max_mass_kg"]:
            rejected[cat] = f"mass {mass:.2f} kg > {rules['max_mass_kg']}"
            continue
        models = []
        for model_id in sorted(inventory[cat]):
            meta = objects_root / cat / model_id / "misc" / "metadata.json"
            if not meta.exists():
                continue
            bbox = [float(v) for v in json.loads(meta.read_text())["bbox_size"]]
            if (max(bbox) <= size["max_extent_m"] and min(bbox) >= size["min_extent_m"]
                    and max(bbox) >= size["min_major_extent_m"]):
                models.append(ModelRecord(model_id, tuple(bbox)))
        if not models:
            rejected[cat] = "no model within size constraints"
            continue
        cats[cat] = EligibleCategory(
            category=cat, synset=syn,
            mass_kg=None if mass is None else round(float(mass), 4),
            lookalike_keys=lookalike_keys(cat, syn, taxonomy,
                                          rules["lookalike"]["max_parent_group"]),
            models=models)
    return ObjectEligibility(version=ELIGIBILITY_VERSION, source=source,
                             categories=cats, rejected=rejected)
